sudo: false
matrix:
  fast_finish: true
  include:
    - language: python
      python:
        - 2.7
          env: TOXENV=py27
        - 3.6
          env: TOXENV=py36
      install:
        - pip install tox
      script:
        - tox
    - language: java
      script:
        - mvn clean verify
notifications:
  email: false
